image: docker:stable
services:
- docker:dind

stages:
- build
- test
- release

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/centos-java-buildpack:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/centos-java-buildpack:latest

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t "$CONTAINER_TEST_IMAGE" .
    - docker push "$CONTAINER_TEST_IMAGE"

test:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE mvn -version
    - docker run $CONTAINER_TEST_IMAGE yarn --version
    - docker run $CONTAINER_TEST_IMAGE npm --version
    - docker run $CONTAINER_TEST_IMAGE git lfs --version
    - docker run $CONTAINER_TEST_IMAGE git --version

release-image:
  stage: release
  script:
    - docker pull "$CONTAINER_TEST_IMAGE"
    - docker tag "$CONTAINER_TEST_IMAGE" "$CONTAINER_RELEASE_IMAGE"
    - docker push "$CONTAINER_RELEASE_IMAGE"
  only:
    - master
